

apiRules:
# Exclude System.Object or System.Reflection to avoid having .Equals and stuff in the docs
- exclude:
    uidRegex: ^System\.

# hides things like Microsoft.Extensions.DependencyInjection etc.
- exclude:
    uidRegex: ^Microsoft\.


# Exclude any tests
- exclude:
    uidRegex: ^Oqtane.Test\.

# Exclude anything marked as PrivateApi
# In future, we may change this to only show things which are PublicApi (recommendation of iJungleboy)
- exclude:
    hasAttribute:
      uid: Oqtane.Documentation.PrivateApi
  